create table if not exists countries
(
    id_country   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_country VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_countries PRIMARY KEY (id_country)
);