create table if not exists roles
(
    id_role   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_role VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id_role)
);