create table if not exists users
(
    id_user       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_user     VARCHAR(50)                             NOT NULL,
    login_user    VARCHAR(20)                             NOT NULL,
    password_user VARCHAR(30)                             NOT NULL,
    id_role       BIGINT,
    id_company    BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id_user)
);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ID_COMPANY FOREIGN KEY (id_company) REFERENCES companies (id_company);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ID_ROLE FOREIGN KEY (id_role) REFERENCES roles (id_role);
