create table if not exists statuses
(
    id_status   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_status VARCHAR(15)                             NOT NULL,
    CONSTRAINT pk_statuses PRIMARY KEY (id_status)
);