create table if not exists meetings
(
    id_meeting      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title_meeting   VARCHAR(255)                            NOT NULL,
    date_meeting    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    address_meeting VARCHAR(100),
    id_country      BIGINT,
    id_status       BIGINT,
    CONSTRAINT pk_meetings PRIMARY KEY (id_meeting)
);

ALTER TABLE meetings
    ADD CONSTRAINT FK_MEETINGS_ON_ID_COUNTRY FOREIGN KEY (id_country) REFERENCES countries (id_country);

ALTER TABLE meetings
    ADD CONSTRAINT FK_MEETINGS_ON_ID_STATUS FOREIGN KEY (id_status) REFERENCES statuses (id_status);