create table if not exists speakers
(
    id_speaker   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_speaker VARCHAR(40)                             NOT NULL,
    CONSTRAINT pk_speakers PRIMARY KEY (id_speaker)
);